# Generated by Django 5.0.6 on 2024-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=254, unique=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('conferences', models.ManyToManyField(to='event_registration.conference')),
                ('role', models.ManyToManyField(to='event_registration.role')),
            ],
            options={
                'ordering': ['reg_date'],
            },
        ),
    ]
