# Generated by Django 5.0.6 on 2024-05-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confuser',
            name='role',
        ),
        migrations.AddField(
            model_name='confuser',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_registration.role'),
            preserve_default=False,
        ),
    ]
